### ISSUE TITLE
Exception "java.lang.NoClassDefFoundError: com/google/common/collect/Multimap"

### ISSUE THREAD

**Issue by Beleggrodion** [btactic/zmblobrescue#1]
Hi,

I found your script, and wanted to try to restore many missing blobs on a multi-server enviroment, because someone moved mailboxes from server A to server B and something went wrong, so that around 9k blobs are missing.  We found a vm backup of  server A before the move to server B, but because now are around 3 weeks after the move their is no option to simple do a restore.

So i mounted on server B the blob store of the backup and tried your script, because the paths, are not exatly the same.

`./zmblobrescue.sh -v --lostfound-dir /mnt/old_store/ --suggested-repair-commands-file /opt/zimbra/tmp/blobtest/ start`

But i receive the following error messsage:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
        at com.zimbra.common.util.CliUtil.getOption(CliUtil.java:68)
        at com.zimbra.common.util.CliUtil.hasOption(CliUtil.java:80)
        at com.zimbra.cs.store.file.BlobConsistencyRescue.parseArgs(BlobConsistencyRescue.java:130)
        at com.zimbra.cs.store.file.BlobConsistencyRescue.main(BlobConsistencyRescue.java:302)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 4 more
`

The used zimbra version is the following:
Zimbra: Release 8.8.15.GA.4177.UBUNTU20.64 UBUNTU20_64 NETWORK edition, Patch 8.8.15_P29.
OS: Ubuntu 20.04.3 LTS
Java: openjdk 13.0.1 2019-10-15

So is this a bug or is something wrong with the lostfound-dir because it's not a flat directory?

Greetings
Beleggrodion

**Comment by adriangibanelbtactic** [comment]
Hi, I didn't notice your bug till today.

Have you used v1.0 (the default from the documentation)?
You should use v1.1 instead which it's the latest tag and has support for ZCS 8.8.X.

If the problem persists even using v1.1 then this is probably the `com/google/common/collect/Multimap` not being found because it's now found in another jar. Maybe because java jars are different between Ubuntu 18.04 and Ubuntu 20.04 ZCS 8.8.15 releases.

You might want to rgrep for Multimap in /opt/zimbra/jars/ and see if you can add that specificar jar to the .sh file.
